export const itemsMock = [
  {
    id: 1,
    brand: "Iphone",
    title: "iPhone 9",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum voluptatem ab iste voluptatibus numquam cupiditate fugiat at placeat repellendus qui obcaecati quisquam, veritatis perspiciatis tempore molestias culpa quibusdam vel exercitationem!",
    price: 999,
    thumbnail: "https://dummyjson.com/image/i/products/1/thumbnail.jpg",
  },
  {
    id: 2,
    brand: "Iphone",
    title: "iPhone 9",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum voluptatem ab iste voluptatibus numquam cupiditate fugiat at placeat repellendus qui obcaecati quisquam, veritatis perspiciatis tempore molestias culpa quibusdam vel exercitationem!",
    price: 999,
    thumbnail: "https://dummyjson.com/image/i/products/1/thumbnail.jpg",
  },
  {
    id: 3,
    brand: "Iphone",
    title: "iPhone 9",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum voluptatem ab iste voluptatibus numquam cupiditate fugiat at placeat repellendus qui obcaecati quisquam, veritatis perspiciatis tempore molestias culpa quibusdam vel exercitationem!",
    price: 999,
    thumbnail: "https://dummyjson.com/image/i/products/1/thumbnail.jpg",
  },
  {
    id: 4,
    brand: "Iphone",
    title: "iPhone 9",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum voluptatem ab iste voluptatibus numquam cupiditate fugiat at placeat repellendus qui obcaecati quisquam, veritatis perspiciatis tempore molestias culpa quibusdam vel exercitationem!",
    price: 999,
    thumbnail: "https://dummyjson.com/image/i/products/1/thumbnail.jpg",
  },
  {
    id: 5,
    brand: "Iphone",
    title: "iPhone 9",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum voluptatem ab iste voluptatibus numquam cupiditate fugiat at placeat repellendus qui obcaecati quisquam, veritatis perspiciatis tempore molestias culpa quibusdam vel exercitationem!",
    price: 999,
    thumbnail: "https://dummyjson.com/image/i/products/1/thumbnail.jpg",
  },
  {
    id: 6,
    brand: "Iphone",
    title: "iPhone 9",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum voluptatem ab iste voluptatibus numquam cupiditate fugiat at placeat repellendus qui obcaecati quisquam, veritatis perspiciatis tempore molestias culpa quibusdam vel exercitationem!",
    price: 999,
    thumbnail: "https://dummyjson.com/image/i/products/1/thumbnail.jpg",
  },
  
]