export enum SubCategoryEnum {
  "smartphones" = "Смартфоны",
  "laptops" = "Ноутбуки",
  "fragrances" = "Парфюм",
  "skincare" = "Забота о коже",
  "groceries" = "Продукты",
  "decoration" = "Уют",
  "furniture" = "Мебель",
  "tops" = "Топы",
  "womens-dresses" = "Женская одежда",
  "womens-shoes" = "Женская обувь",
  "mens-shirts" = "Мужские футболки",
  "mens-shoes" = "Обувь",
  "mens-watches" = "Часы",
  "womens-watches" = "Женские Часы",
  "womens-bags" = "Сумочки",
  "womens-jewellery" = "Украшения",
  "sunglasses" = "Очки",
  "automotive" = "Авто аксессуары",
  "motorcycle" = "Мотоциклы",
  "lighting" = "Освещение",
};
