export enum SubCategoryEnum {
  "smartphones" = "Смартфоны",
  "laptops" = "Ноутбуки",
  "fragrances" = "Парфюм",
  "skincare" = "Забота о коже",
  "groceries" = "Продукты",
  "decoration" = "Уют",
  "furniture" = "Мебель",
  "tops" = "Топы",
  "womensDresses" = "Женская одежда",
  "womensShoes" = "Женская обувь",
  "mensShirts" = "Мужские футболки",
  "mensShoes" = "Обувь",
  "mensWatches" = "Часы",
  "womensWatches" = "Женские Часы",
  "womensBags" = "Сумочки",
  "womensJewellery" = "Украшения",
  "sunglasses" = "Очки",
  "automotive" = "Авто аксессуары",
  "motorcycle" = "Мотоциклы",
  "lighting" = "Освещение",
};
